name:                webapp
version:             0.1.0.0
github:              "micwypych/webapp"
license:             BSD3
author:              "Michał Wypych"
maintainer:          "mwypych@agh.edu.pl"
copyright:           "2019 Michał Wypych"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-empty-project-plain#readme>

dependencies:
- base >= 4.7 && < 5
- text
- HDBC >= 2.4
- HDBC-sqlite3 >= 2.3
- convertible
- aeson
- attoparsec
- scotty
- http-types
- wai
- transformers

library:
  source-dirs: src
  ghc-options:
      - -Wall
      - -fwarn-tabs
  default-extensions: 
    - OverloadedStrings

executables:
  webapp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -fwarn-tabs
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webapp

tests:
  webapp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webapp
    - HUnit
    default-extensions: 
    - OverloadedStrings

