flags: {}
packages:
- .
system-ghc: true
extra-deps:
- text-1.2.3.1
- HDBC-2.4.0.1
- HDBC-sqlite3-2.3.3.1
- convertible-1.1.1.0
- mtl-2.2.1
- old-time-1.1.0.3
- utf8-string-1.0.1.1
- old-locale-1.0.0.7
- aeson-0.11.2.1
resolver: lts-6.27
